### ISSUE TITLE
Expose constants for standard OCI image annotations

### ISSUE THREAD

**Issue by JamieMagee** [mthalman/DockerRegistryClient#16]
Currently manifest annotations are exposed as a dictionary:

https://github.com/mthalman/DockerRegistryClient/blob/c60e6dc68fc8f61f4ceaca4b4be1cba388985487/src/Valleysoft.DockerRegistryClient/Models/OciManifest.cs#L12-L13

Is it possible to ship constants for [standard annotation keys][1]?

```C#
public static class AnnotationConstants
{
    public const string ArtifactCreated = "org.opencontainers.artifact.created";

    public const string ArtifactDescription = "org.opencontainers.artifact.description";
}
```

which could be used like

```C#
if (manifest.Annotations.TryGetValue(AnnotationConstants.ArtifactCreated, out var artifactCreated)
{
    // do something here
}
```

[1]: https://github.com/opencontainers/image-spec/blob/188d3a4e194241cf3412010a6c1073a71d4b0708/annotations.md#pre-defined-annotation-keys

**Comment by mthalman** [comment]
How does this look? https://github.com/mthalman/DockerRegistryClient/pull/17
